# Generated by Django 4.1.5 on 2023-02-26 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpassapp.vault')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('R', 'READ'), ('W', 'WRITE'), ('O', 'OWNER')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpassapp.account')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpassapp.vault')),
            ],
        ),
        migrations.CreateModel(
            name='AccountVaultAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('R', 'READ'), ('W', 'WRITE'), ('O', 'OWNER')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpassapp.account')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpassapp.vault')),
            ],
        ),
    ]
