# Generated by Django 4.1.7 on 2023-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpassapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='image_path',
            field=models.FilePathField(path='images'),
        ),
    ]
