# Generated by Django 4.1.5 on 2023-03-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpassapp', '0002_alter_vault_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='image_path',
            field=models.FilePathField(path='C:\\DEV\\troisieme\\DevWeb\\FirstPass\\api\\firstpass\\files\\images'),
        ),
    ]
