# Generated by Django 4.1.5 on 2023-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpassapp', '0003_alter_vault_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='image_path',
            field=models.FilePathField(path='D:\\Dev\\Arc\\FirstPass\\api\\firstpass\\files\\images'),
        ),
    ]
