# Generated by Django 4.1.5 on 2023-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpassapp', '0004_alter_vault_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
