# Generated by Django 4.1.5 on 2023-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstpassapp', '0005_alter_vault_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='image_path',
            field=models.CharField(max_length=255),
        ),
    ]
